# Generated by Django 4.1 on 2024-06-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_sources', models.CharField(max_length=50)),
                ('waste_collection', models.CharField(max_length=50)),
                ('transportation', models.CharField(max_length=50)),
                ('waste_separation', models.CharField(max_length=50)),
                ('waste_treatment', models.CharField(max_length=50)),
                ('waste_disposal', models.CharField(max_length=50)),
            ],
        ),
    ]
