# Generated by Django 4.1 on 2024-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_app', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('waste_sources', models.CharField(max_length=50)),
                ('waste_collection', models.CharField(max_length=50)),
                ('transportation', models.CharField(max_length=50)),
                ('waste_separation', models.CharField(max_length=50)),
                ('waste_treatment', models.CharField(max_length=50)),
                ('waste_disposal', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Waste',
        ),
    ]
